source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!
use_modular_headers!

def pods
  # ITMS-90809: Deprecated API Usage 移除UIWebView
  pod 'AFNetworking', '3.2.1', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']

  pod 'Masonry', '1.1.0'
  pod 'YYModel', '1.0.4'
  pod 'ReactiveObjC', '3.1.1'
  pod 'MBProgressHUD', '1.1.0'
  pod 'SDWebImage', '5.4.2'
  pod 'MJRefresh', '3.3.1'
  pod 'JLRoutes', '2.1'
  pod 'YTKNetwork', '2.1.4'
  pod 'WechatOpenSDK', '1.8.4'
  pod 'JLLogEncoding', '0.0.3' #解决控制台输出不显示中文
  pod 'UITextView+Placeholder'
  pod 'AliyunOSSiOS', '2.10.8'
  pod 'DZNEmptyDataSet', '1.8.1'
  pod 'YYImage', '1.0.4'
  pod 'KTVHTTPCache', '2.0.1'
  pod 'JXCategoryView', '1.5.2'
  pod 'IQKeyboardManager', '6.5.4'
  pod 'HWPanModal', '~> 0.6.7'
  
  # 友盟
  pod 'UMCCommon', '2.1.1'
  pod 'UMCAnalytics', '6.0.5'
  pod 'UMCPush', '3.2.4'
  pod 'UMCSecurityPlugins', '1.0.6'
  pod 'UMCShare/UI', '6.9.6'
  pod 'UMCShare/Social/ReducedQQ', '6.9.6'
  pod 'UMCShare/Social/ReducedWeChat', '6.9.6'
  
  # firebase
  pod 'Fabric', '1.10.2'
  pod 'Crashlytics', '3.14.0'
  pod 'Firebase/Analytics', '6.14.0'
  
  # swift
  pod 'lottie-ios', '3.1.5'
  pod 'SnapKit', '5.0.1'
  pod 'RxSwift', '5.0.1'
  pod 'RxCocoa', '5.0.1'
  pod 'SQLite.swift', '0.12.2'
  pod 'SwiftEntryKit', '1.2.3'
  
  # local
  pod 'DKCamera', :path => './ImagePicker/DKCamera'
  pod 'DKPhotoGallery', :path => './ImagePicker/DKPhotoGallery'
  pod 'DKImagePickerController', :path => './ImagePicker/DKImagePickerController'

end	

target 'ChalkTalks' do
  pods
  pod 'MLeaksFinder', :configuration => ['Debug']
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
      # if target.name.eql?('CropViewController')
      #   config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = '${PODS_ROOT}/CropViewController/Swift/CropViewController/CropViewController.h'
      # end
      # if target.name.eql?('FLAnimatedImage')
      #   config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = '${PODS_ROOT}/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h'
      # end
      # if target.name.eql?('RxCocoa')
      #   config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = '${PODS_ROOT}/RxCocoa/RxCocoa/RxCocoa.h'
      # end
      # config.build_settings['ENABLE_BITCODE'] = 'NO'
      # config.build_settings['VALID_ARCHS'] = 'arm64e arm64'
      # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      # config.build_settings['SWIFT_VERSION'] = '5.1.3'
#     end
#   end
# end
